openapi: 3.1.0
info:
  title: space traders interface
  version: '0.1'
  servers:
    - url: 'http://localhost:8080'
paths:
  '/ships/{ship_id}':
    parameters:
      - schema:
          type: integer
        name: ship_id
        in: path
        required: true
    get:
      summary: ship info
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  type:
                    type: string
                  location:
                    type: string
      operationId: getShip-ship_id
      description: Retrieve a specific ship by ID