openapi: 3.1.0
info:
  title: space traders interface
  version: '0.1'
  servers:
    - url: 'http://localhost:8080'
basePath: '/api/v1'
paths:
  '/agents':
    post:
      summary: create agent
      tags: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AgentRequest'
      responses:
        '201':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Agent'
      operationId: createAgent
      description: Create a new agent
    get:
      summary: list agents
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Agent'
      operationId: listAgents
      description: List all agents
  '/agents/{callSign}':
    parameters:
      - schema:
          type: string
        name: callSign
        in: path
        required: true
    get:
      summary: agent information
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Agent'
      operationId: getAgent-callSign
      description: Retrieve a specific agent by call sign
  '/agents/{callSign}/refresh':
    parameters:
      - schema:
          type: string
        name: callSign
        in: path
        required: true
    put:
      summary: refresh agent
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
              $ref: '#/components/schemas/Agent'
      operationId: refreshAgent-callSign
      description: Refresh an agent with the spacetraders backend
  '/ships/{ship_id}':
    parameters:
      - schema:
          type: integer
        name: ship_id
        in: path
        required: true
    get:
      summary: ship info
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Ship'
      operationId: getShip-ship_id
      description: Retrieve a specific ship by ID
components:
    schemas:
      Agent:
        type: object
        properties:
            id:
              type: integer
            faction:
              type: string
            headquarters:
              type: string
            callSign:
              type: string
            credits:
              type: integer
      AgentRequest:
        type: object
        required:
          - faction
          - headquarters
          - callSign
        properties:
          faction:
            type: string
          headquarters:
            type: string
          callSign:
            type: string
          credits:
            type: integer
          expiresOn:
            type: string
            format: date
      Ship:
        type: object
        properties:
          id:
            type: integer
          location:
            type: string