POST http://localhost:8080/agents
Content-Type: application/json

{
    "callSign": "SHUGGIE",
    "headquarters": "X1-JN40-A1",
    "credits": 175000,
    "faction": "COSMIC"
}

###
GET http://localhost:8080/agents/SHUGGIE
