# curl --request POST
# --url 'https://api.spacetraders.io/v2/register'
# --header 'Content-Type: application/json'
# --data '{
#    "symbol": "INSERT_CALLSIGN_HERE",
#    "faction": "COSMIC"
#   }'
POST https://api.spacetraders.io/v2/register
Content-Type: application/json

{
  "symbol": "SHUGGIE",
  "faction": "COSMIC"
}

###

# curl 'https://api.spacetraders.io/v2/my/agent'
# --header 'Authorization: Bearer INSERT_TOKEN_HERE'
GET https://api.spacetraders.io/v2/my/agent

###



